### ISSUE TITLE
Is there a way to convert shapefile to the STREAMobj ?

### ISSUE THREAD

**Issue by 2179856994** [csdms-contrib/topotoolbox#9]
Dear Mr.Schwanghart,
Thank you for your reading.I want to use the streamnet which I got this shapefile from GIS. Is there a way to convert shapefile to the STREAMobj ?

**Comment by wschwanghart** [comment]
Hi. Please read [this blog post](https://topotoolbox.wordpress.com/2022/06/01/stream-burning-or-how-to-convert-a-shapefile-to-a-streamobj/) on converting shapefiles to STREAMobjs. Best regards, Wolfgang
